"""
16S Consensus Pipeline - Main Snakefile

This pipeline was built specifically to process Oxford Nanopore long-read 16S rRNA sequencing data
to generate consensus sequences for each sample.
"""

configfile: "workflow/default_config.yaml"

include: "rules/common.smk"
include: "rules/1_preprocessing.smk"
include: "rules/2_align.smk"
include: "rules/3_naive_consensus.smk"
include: "rules/4_clustering.smk"
include: "rules/5_cluster_consensus.smk"
include: "rules/6_summary.smk"

rule all:
    """
    Default target: generate both naive and multi-consensus databases and summary report.
    """
    input:
        # Checkpoint outputs
        CHECK_DIR / "read_check_summary.tsv",
        CHECK_DIR / "filtered_check_summary.tsv",
        # Final pooled databases
        NAIVE_DATABASE_FILE,
        MULTI_DATABASE_FILE,
        # Analysis outputs
        PAIRWISE_DISTANCE_HEATMAP_FILE,
        QC_ALIGNMENT_FILE,
        # Summary report
        PIPELINE_SUMMARY_FILE,
        QC_DIR / "global_consensus.fasta"
    default_target: True

